FROM ubuntu:latest

RUN apt-get update && apt-get install --yes \
    clang \
    cmake \
    git \
    libboost-program-options-dev \
    libx11-dev \
    libxcursor-dev \
    libxinerama-dev \
    libxrandr-dev \
    make \
    mesa-common-dev
